
import java.util.ArrayList;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author tessl
 */
public class FenetreQuiz extends javax.swing.JFrame {
    private ArrayList<question> listeQuestions;
    private int indexQuestionCourante = 0;
    private int score = 0;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FenetreQuiz.class.getName());

    /**
     * Creates new form FenetreQuiz
     */
    public FenetreQuiz() {
        initComponents();
         initialiserQuestions();
        afficherQuestionCourante();
       
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblQuestion = new javax.swing.JLabel();
        btnRep1 = new javax.swing.JButton();
        btnRep2 = new javax.swing.JButton();
        btnRep3 = new javax.swing.JButton();
        btnRep4 = new javax.swing.JButton();
        lblFeedback = new javax.swing.JLabel();
        QuestionSuivante = new javax.swing.JButton();
        lblScore = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblQuestion.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        lblQuestion.setForeground(new java.awt.Color(204, 0, 51));
        lblQuestion.setText("question");
        getContentPane().add(lblQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 82, 540, -1));

        btnRep1.setText("reponse 1");
        btnRep1.setActionCommand("reponse 1");
        btnRep1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnRep1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 165, -1));

        btnRep2.setText("reponse 2");
        btnRep2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnRep2, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 143, 134, -1));

        btnRep3.setText("reponse 3");
        btnRep3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnRep3, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 143, 125, -1));

        btnRep4.setText("reponse 4");
        btnRep4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep4ActionPerformed(evt);
            }
        });
        getContentPane().add(btnRep4, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 197, 125, -1));

        lblFeedback.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblFeedback.setForeground(new java.awt.Color(153, 0, 255));
        lblFeedback.setText("jLabel1");
        getContentPane().add(lblFeedback, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 54, 250, -1));

        QuestionSuivante.setForeground(new java.awt.Color(51, 0, 255));
        QuestionSuivante.setText("question suivante ");
        QuestionSuivante.setActionCommand("question suivante ");
        QuestionSuivante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuestionSuivanteActionPerformed(evt);
            }
        });
        getContentPane().add(QuestionSuivante, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 150, -1));

        lblScore.setText("score");
        getContentPane().add(lblScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 6, 130, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void QuestionSuivanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuestionSuivanteActionPerformed
          indexQuestionCourante++;
        if (indexQuestionCourante < listeQuestions.size()) {
            afficherQuestionCourante();
        } else {
            lblQuestion.setText("FIN DU QUIZ !");
            lblFeedback.setText("Quiz terminé. Score final : " + score + " / " + listeQuestions.size());
            QuestionSuivante.setEnabled(false);
            lblScore.setText("Score final : " + score + " / " + listeQuestions.size());
        }
    }//GEN-LAST:event_QuestionSuivanteActionPerformed

    private void btnRep4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep4ActionPerformed
        verifierReponse(4);
    }//GEN-LAST:event_btnRep4ActionPerformed

    private void btnRep3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep3ActionPerformed
        verifierReponse(3);
    }//GEN-LAST:event_btnRep3ActionPerformed

    private void btnRep2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep2ActionPerformed
        verifierReponse(2);
    }//GEN-LAST:event_btnRep2ActionPerformed

    private void btnRep1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep1ActionPerformed
        verifierReponse(1);
    }//GEN-LAST:event_btnRep1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FenetreQuiz().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton QuestionSuivante;
    private javax.swing.JButton btnRep1;
    private javax.swing.JButton btnRep2;
    private javax.swing.JButton btnRep3;
    private javax.swing.JButton btnRep4;
    private javax.swing.JLabel lblFeedback;
    private javax.swing.JLabel lblQuestion;
    private javax.swing.JLabel lblScore;
    // End of variables declaration//GEN-END:variables

    private void initialiserQuestions() {
       listeQuestions = new ArrayList<>();

listeQuestions.add(new question(
    "Le pingouin vole ?",
    "Oui", "Non", "Parfois", "Seulement le dimanche",
    2));

listeQuestions.add(new question(
    "Couleur d’un nuage heureux ?",
    "Bleu", "Rose", "Blanc", "Arc-en-ciel",
    3));

listeQuestions.add(new question(
    "Animal le plus nul au cache-cache ?",
    "Girafe", "Poisson", "Panda", "Mouton",
    1));

listeQuestions.add(new question(
    "Boisson préférée d’un robot ?",
    "Huile", "Café", "Batterie", "Eau",
    1));

listeQuestions.add(new question(
    "Bruitage d’une limace rapide ?",
    "Zoom", "Sploutch", "Tchou", "…",
    1));
        
    }

    private void afficherQuestionCourante() {
           if (indexQuestionCourante >= listeQuestions.size()) {
            return;
        }
       
        question question = listeQuestions.get(indexQuestionCourante);
       
        lblQuestion.setText(question.getIntitule());
       
        btnRep1.setText(question.getProposition1());
        btnRep2.setText(question.getProposition2());
        btnRep3.setText(question.getProposition3());
        btnRep4.setText(question.getProposition4());
       
        btnRep1.setEnabled(true);
        btnRep2.setEnabled(true);
        btnRep3.setEnabled(true);
        btnRep4.setEnabled(true);
       
        QuestionSuivante.setEnabled(false);
       
        lblFeedback.setText("Choisissez une réponse...");
        lblScore.setText("Score : " + score + " / " + listeQuestions.size());
    }
     private void verifierReponse(int reponseChoisie) {
        question questionCourante = listeQuestions.get(indexQuestionCourante);

        if (reponseChoisie == questionCourante.getIndexBonneReponse()) {
            lblFeedback.setText("Bonne réponse !!!");
            score++;
        } else {
            lblFeedback.setText("Mauvaise réponse. La bonne réponse était la proposition " + questionCourante.getIndexBonneReponse() + ".");
        }
       
        btnRep1.setEnabled(false);
        btnRep2.setEnabled(false);
        btnRep3.setEnabled(false);
        btnRep4.setEnabled(false);
       
        QuestionSuivante.setEnabled(true);
       
        lblScore.setText("Score : " + score + " / " + (indexQuestionCourante + 1));
    }
    }


