/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author tessl
 */
public class interfacegraphique extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(interfacegraphique.class.getName());
    private int nbClics;

    /**
     * Creates new form interfacegraphique
     */
    public interfacegraphique() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        YOOOO = new javax.swing.JLabel();
        bouton_principal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        YOOOO.setFont(new java.awt.Font("Segoe UI Emoji", 2, 24)); // NOI18N
        YOOOO.setForeground(new java.awt.Color(255, 0, 255));
        YOOOO.setText("bonjour");

        bouton_principal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bouton_principal.setForeground(new java.awt.Color(51, 255, 204));
        bouton_principal.setText("double dab");
        bouton_principal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton_principalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(bouton_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(YOOOO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(YOOOO)
                .addGap(18, 18, 18)
                .addComponent(bouton_principal)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bouton_principalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_principalActionPerformed
        // TODO add your handling code here:
       if (nbClics ==0) YOOOO.setText("on sors ?");
       if (nbClics ==1) YOOOO.setText("alcool a volonte");
       if (nbClics ==2) YOOOO.setText("y'a ton crush en plus");
       if (nbClics ==3) YOOOO.setText("tu dors chez moi ?");
       if (nbClics ==4) YOOOO.setText("tu n'a pas le choix");
       if (nbClics ==5) YOOOO.setText("a ce soir ");
       nbClics++;
       
        
    }//GEN-LAST:event_bouton_principalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new interfacegraphique().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel YOOOO;
    private javax.swing.JButton bouton_principal;
    // End of variables declaration//GEN-END:variables
}
