/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
 
public class Choixniveau extends javax.swing.JFrame {
    private final interfacecadenas jeuInterface;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Choixniveau.class.getName());

    /**
     * Creates new form commejeveux
     * @param jeuInterface
     */
    public Choixniveau(interfacecadenas jeuInterface) {
        interfacecadenas interfaceRef = null;
      this.jeuInterface = interfaceRef;
        initComponents();
        // Optionnel : Centrer la fenêtre de choix au milieu de l'écran
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bouton_facile = new javax.swing.JButton();
        bouton_difficile = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bouton_facile.setText("Niveau facile ");
        bouton_facile.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 255, 204), new java.awt.Color(51, 255, 204), new java.awt.Color(0, 255, 204), new java.awt.Color(0, 255, 204)));
        bouton_facile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton_facileActionPerformed(evt);
            }
        });

        bouton_difficile.setText("Niveau difficile");
        bouton_difficile.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 255, 204), new java.awt.Color(0, 255, 204), new java.awt.Color(0, 255, 204), new java.awt.Color(0, 255, 204)));
        bouton_difficile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton_difficileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(bouton_facile, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(bouton_difficile, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bouton_facile)
                    .addComponent(bouton_difficile))
                .addContainerGap(151, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bouton_facileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_facileActionPerformed
       bouton_facile.setText("Facile (7 tentatives)");
        bouton_facile.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton_facileActionPerformed(evt);
            }
        });
        getContentPane().add(bouton_facile);
        
    }//GEN-LAST:event_bouton_facileActionPerformed

    private void bouton_difficileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_difficileActionPerformed
        // TODO add your handling code herebouton_difficile.setText("Difficile (3 tentatives)");
        bouton_difficile.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton_difficileActionPerformed(evt);
            }
        });
        getContentPane().add(bouton_difficile);

        pack();
    }//GEN-LAST:event_bouton_difficileActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Choixniveau(null).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bouton_difficile;
    private javax.swing.JButton bouton_facile;
    // End of variables declaration//GEN-END:variables
}
